id: Maltiverse Test
version: -1
name: Maltiverse Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: e04de233-bb30-4bba-86ce-6a072f32302f
    type: start
    task:
      id: e04de233-bb30-4bba-86ce-6a072f32302f
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: d8f3618a-53ed-476d-8728-7c79d4e6dc38
    type: regular
    task:
      id: d8f3618a-53ed-476d-8728-7c79d4e6dc38
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: eb8ea395-34d7-45f9-80e5-3f7d0c4339de
    type: regular
    task:
      id: eb8ea395-34d7-45f9-80e5-3f7d0c4339de
      version: -1
      name: ip
      description: Checks the reputation of an IP address
      script: Maltiverse|||ip
      type: regular
      iscommand: true
      brand: Maltiverse
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      fullResponse: {}
      ip:
        simple: 1.1.1.1
      long: {}
      threshold: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: d7ccc3a3-26f7-4c6d-8bd1-2f6670aebc06
    type: condition
    task:
      id: d7ccc3a3-26f7-4c6d-8bd1-2f6670aebc06
      version: -1
      name: VerifyContext
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      scriptName: AreValuesEqual
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "4"
    scriptarguments:
      left:
        simple: ${IP.Address}
      right:
        simple: 1.1.1.1
    results:
    - AreValuesEqual
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: 0086cb7f-db4b-4ada-81d3-a206fac43887
    type: regular
    task:
      id: 0086cb7f-db4b-4ada-81d3-a206fac43887
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: 8a302270-422b-42cc-819c-91db5058e9b0
    type: regular
    task:
      id: 8a302270-422b-42cc-819c-91db5058e9b0
      version: -1
      name: url
      description: Checks the reputation of an URL
      script: Maltiverse|||url
      type: regular
      iscommand: true
      brand: Maltiverse
    nexttasks:
      '#none#':
      - "6"
      - "8"
      - "7"
    scriptarguments:
      fullResponse: {}
      long: {}
      threshold: {}
      url:
        simple: http://assocolours.com/mu/i/LoginVerification.php  # disable-secrets-detection
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: 279f0adc-cc0a-4539-8186-cd1b2565e46d
    type: condition
    task:
      id: 279f0adc-cc0a-4539-8186-cd1b2565e46d
      version: -1
      name: VerifyContext
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      scriptName: AreValuesEqual
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "9"
    scriptarguments:
      left:
        simple: ${URL.Malicious.Vendor}
      right:
        simple: Maltiverse
    results:
    - AreValuesEqual
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "7":
    id: "7"
    taskid: 98d8a2ad-bc45-4750-8db5-c66a32dc90c6
    type: condition
    task:
      id: 98d8a2ad-bc45-4750-8db5-c66a32dc90c6
      version: -1
      name: VerifyContext
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      scriptName: AreValuesEqual
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "9"
    scriptarguments:
      left:
        simple: ${Maltiverse.URL.Hostname}
      right:
        simple: assocolours.com
    results:
    - AreValuesEqual
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "8":
    id: "8"
    taskid: 6df1f3e9-7620-4f5b-821e-b997475562e3
    type: condition
    task:
      id: 6df1f3e9-7620-4f5b-821e-b997475562e3
      version: -1
      name: VerifyContext
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      scriptName: AreValuesEqual
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "9"
    scriptarguments:
      left:
        simple: ${Maltiverse.URL.Tld}
      right:
        simple: com
    results:
    - AreValuesEqual
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "9":
    id: "9"
    taskid: 25eee283-59ed-4057-85b1-eb28694a78dd
    type: regular
    task:
      id: 25eee283-59ed-4057-85b1-eb28694a78dd
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "10":
    id: "10"
    taskid: a0fd55af-4081-430b-8509-9b0ed285ae9f
    type: regular
    task:
      id: a0fd55af-4081-430b-8509-9b0ed285ae9f
      version: -1
      name: domain
      description: Checks the reputation of a Domain
      script: Maltiverse|||domain
      type: regular
      iscommand: true
      brand: Maltiverse
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      domain:
        simple: google.com
      fullResponse: {}
      long: {}
      threshold: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "11":
    id: "11"
    taskid: fbb6bab5-ea1a-44f5-8cc9-ff4e2212e8e7
    type: condition
    task:
      id: fbb6bab5-ea1a-44f5-8cc9-ff4e2212e8e7
      version: -1
      name: VerifyContext
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      scriptName: AreValuesEqual
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "12"
    scriptarguments:
      left:
        simple: ${Maltiverse.Domain.Address}
      right:
        simple: google.com
    results:
    - AreValuesEqual
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1590
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "12":
    id: "12"
    taskid: baa87ff4-1161-4928-8902-4df813a08155
    type: regular
    task:
      id: baa87ff4-1161-4928-8902-4df813a08155
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1770
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "13":
    id: "13"
    taskid: 877a3b61-1fa2-4c07-8a3f-e69c8988e2d5
    type: regular
    task:
      id: 877a3b61-1fa2-4c07-8a3f-e69c8988e2d5
      version: -1
      name: file
      description: Check the reputation of a file
      script: Maltiverse|||file
      type: regular
      iscommand: true
      brand: Maltiverse
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      file:
        simple: c383e5592a8ae962464f57af2e306e0fb5d954cb14091e8ae0df4c3e6e3e2966
      fullResponse: {}
      hash: {}
      long: {}
      threshold: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1945
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "14":
    id: "14"
    taskid: f69ef25d-ecef-4364-8081-5a85dc16af55
    type: condition
    task:
      id: f69ef25d-ecef-4364-8081-5a85dc16af55
      version: -1
      name: VerifyContext
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      scriptName: AreValuesEqual
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "15"
    scriptarguments:
      left:
        simple: ${Maltiverse.File.Name}
      right:
        simple: 1585464001_pafish.exe
    results:
    - AreValuesEqual
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 2120
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "15":
    id: "15"
    taskid: 73198a25-207e-440f-8d7e-d536ccaf473d
    type: title
    task:
      id: 73198a25-207e-440f-8d7e-d536ccaf473d
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 2295
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {
      "6_9_yes": 0.19
    },
    "paper": {
      "dimensions": {
        "height": 2310,
        "width": 1240,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
