id: Maltiverse Test
version: -1
name: Maltiverse Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: e04de233-bb30-4bba-86ce-6a072f32302f
    type: start
    task:
      id: e04de233-bb30-4bba-86ce-6a072f32302f
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: a594d6f9-fe9b-4d8d-88ca-9b5f9b9f168b
    type: regular
    task:
      id: a594d6f9-fe9b-4d8d-88ca-9b5f9b9f168b
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: 4e2a026b-91b9-4627-82cc-ae4bb8dbfb3d
    type: regular
    task:
      id: 4e2a026b-91b9-4627-82cc-ae4bb8dbfb3d
      version: -1
      name: ip
      description: Checks the reputation of an IP address
      script: Maltiverse|||ip
      type: regular
      iscommand: true
      brand: Maltiverse
    nexttasks:
      '#none#':
      - "3"
      - "16"
    scriptarguments:
      fullResponse: {}
      ip:
        simple: 1.1.1.1
      long: {}
      retries: {}
      sampleSize: {}
      threshold: {}
      wait: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 360
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: f7e01d8c-84f8-4d5e-8a68-9c6f8147dbe6
    type: condition
    task:
      id: f7e01d8c-84f8-4d5e-8a68-9c6f8147dbe6
      version: -1
      name: VerifyAddress
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      scriptName: AreValuesEqual
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "4"
    scriptarguments:
      left:
        simple: ${IP.Address}
      right:
        simple: 1.1.1.1
    results:
    - AreValuesEqual
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: 0086cb7f-db4b-4ada-81d3-a206fac43887
    type: regular
    task:
      id: 0086cb7f-db4b-4ada-81d3-a206fac43887
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: 8a302270-422b-42cc-819c-91db5058e9b0
    type: regular
    task:
      id: 8a302270-422b-42cc-819c-91db5058e9b0
      version: -1
      name: url
      description: Checks the reputation of an URL
      script: Maltiverse|||url
      type: regular
      iscommand: true
      brand: Maltiverse
    nexttasks:
      '#none#':
      - "6"
      - "8"
      - "7"
    scriptarguments:
      fullResponse: {}
      long: {}
      threshold: {}
      url:
        simple: http://assocolours.com/mu/i/LoginVerification.php
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: f03f9f4a-4765-41e3-8b5d-d6055a55bc1d
    type: condition
    task:
      id: f03f9f4a-4765-41e3-8b5d-d6055a55bc1d
      version: -1
      name: VerifyVendor
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      scriptName: AreValuesEqual
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "9"
    scriptarguments:
      left:
        simple: ${URL.Malicious.Vendor}
      right:
        simple: Maltiverse
    results:
    - AreValuesEqual
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "7":
    id: "7"
    taskid: 2922514b-0107-48d8-8ecf-9eb4d9b1e6a9
    type: condition
    task:
      id: 2922514b-0107-48d8-8ecf-9eb4d9b1e6a9
      version: -1
      name: VerifyDomainName
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      scriptName: AreValuesEqual
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "9"
    scriptarguments:
      left:
        simple: ${Maltiverse.URL.Hostname}
      right:
        simple: assocolours.com
    results:
    - AreValuesEqual
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "8":
    id: "8"
    taskid: e0816f1c-8d51-43e7-87ca-a80a603aba83
    type: condition
    task:
      id: e0816f1c-8d51-43e7-87ca-a80a603aba83
      version: -1
      name: VerifyTLD
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      scriptName: AreValuesEqual
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "9"
    scriptarguments:
      left:
        simple: ${Maltiverse.URL.Tld}
      right:
        simple: com
    results:
    - AreValuesEqual
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "9":
    id: "9"
    taskid: 25eee283-59ed-4057-85b1-eb28694a78dd
    type: regular
    task:
      id: 25eee283-59ed-4057-85b1-eb28694a78dd
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "10":
    id: "10"
    taskid: 4b8a25cd-e7b6-4e6a-8294-7412c8bdaf27
    type: regular
    task:
      id: 4b8a25cd-e7b6-4e6a-8294-7412c8bdaf27
      version: -1
      name: domain
      description: Checks the reputation of a Domain
      script: Maltiverse|||domain
      type: regular
      iscommand: true
      brand: Maltiverse
    nexttasks:
      '#none#':
      - "11"
      - "17"
    scriptarguments:
      domain:
        simple: google.com
      fullResponse: {}
      long: {}
      retries: {}
      sampleSize: {}
      threshold: {}
      wait: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "11":
    id: "11"
    taskid: d5e1a7f3-6707-485f-88dc-c45de5cc24a4
    type: condition
    task:
      id: d5e1a7f3-6707-485f-88dc-c45de5cc24a4
      version: -1
      name: VerifyDomainName
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      scriptName: AreValuesEqual
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "12"
    scriptarguments:
      left:
        simple: ${Maltiverse.Domain.Address}
      right:
        simple: google.com
    results:
    - AreValuesEqual
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "12":
    id: "12"
    taskid: baa87ff4-1161-4928-8902-4df813a08155
    type: regular
    task:
      id: baa87ff4-1161-4928-8902-4df813a08155
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1770
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "13":
    id: "13"
    taskid: 7e1b518b-69b3-46fe-853c-4ee617769079
    type: regular
    task:
      id: 7e1b518b-69b3-46fe-853c-4ee617769079
      version: -1
      name: file
      description: Check the reputation of a file
      script: Maltiverse|||file
      type: regular
      iscommand: true
      brand: Maltiverse
    nexttasks:
      '#none#':
      - "14"
      - "18"
    scriptarguments:
      file:
        simple: c383e5592a8ae962464f57af2e306e0fb5d954cb14091e8ae0df4c3e6e3e2966
      fullResponse: {}
      hash: {}
      long: {}
      retries: {}
      threshold: {}
      wait: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1945
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "14":
    id: "14"
    taskid: c5367ba8-ddcc-44ce-80fd-2ae92a5f61c8
    type: condition
    task:
      id: c5367ba8-ddcc-44ce-80fd-2ae92a5f61c8
      version: -1
      name: VerifyFileName
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      scriptName: AreValuesEqual
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "15"
    scriptarguments:
      left:
        simple: ${Maltiverse.File.Name}
      right:
        simple: 1585464001_pafish.exe
    results:
    - AreValuesEqual
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 2120
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "15":
    id: "15"
    taskid: 73198a25-207e-440f-8d7e-d536ccaf473d
    type: title
    task:
      id: 73198a25-207e-440f-8d7e-d536ccaf473d
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 2295
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "16":
    id: "16"
    taskid: c470ef70-dc18-4f1b-8c08-e5293bebcd1e
    type: condition
    task:
      id: c470ef70-dc18-4f1b-8c08-e5293bebcd1e
      version: -1
      name: VerifyVendor
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      scriptName: AreValuesEqual
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "4"
    scriptarguments:
      left:
        simple: ${DBotScore.Vendor}
      right:
        simple: Maltiverse
    results:
    - AreValuesEqual
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "17":
    id: "17"
    taskid: 9ae46c4c-4083-474d-854b-c43435a70124
    type: condition
    task:
      id: 9ae46c4c-4083-474d-854b-c43435a70124
      version: -1
      name: VerifyDomainTld
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      scriptName: AreValuesEqual
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "12"
    scriptarguments:
      left:
        simple: ${Maltiverse.Domain.Tld}
      right:
        simple: com
    results:
    - AreValuesEqual
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "18":
    id: "18"
    taskid: 7b6711a2-21ee-4c62-8733-53ce994995eb
    type: condition
    task:
      id: 7b6711a2-21ee-4c62-8733-53ce994995eb
      version: -1
      name: VerifyFileHash
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      scriptName: AreValuesEqual
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "15"
    scriptarguments:
      left:
        simple: ${Maltiverse.File.ProcessList.Sha256}
      right:
        simple: c383e5592a8ae962464f57af2e306e0fb5d954cb14091e8ae0df4c3e6e3e2966
    results:
    - AreValuesEqual
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 2120
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {
      "6_9_yes": 0.19
    },
    "paper": {
      "dimensions": {
        "height": 2310,
        "width": 1240,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
