id: GooglePubSub_Test
version: -1
name: GooglePubSub_Test
fromversion: 5.0.0
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 3658a7aa-d5ea-4b01-8fb2-1804d570053d
    type: start
    task:
      id: 3658a7aa-d5ea-4b01-8fb2-1804d570053d
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "15"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: 644519bd-51e8-4ed0-8100-48cbd0ae8e04
    type: regular
    task:
      id: 644519bd-51e8-4ed0-8100-48cbd0ae8e04
      version: -1
      name: DeleteContext
      script: DeleteContext
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: 1856a1b8-1859-44af-88a0-539b534d76a3
    type: regular
    task:
      id: 1856a1b8-1859-44af-88a0-539b534d76a3
      version: -1
      name: google-cloud-pubsub-topics-list
      script: '|||google-cloud-pubsub-topics-list'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      page_size: {}
      page_token: {}
      project_id:
        simple: gcp-integrations
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: 4f6b8a30-2a11-4924-8ac8-ce0c3bddcb62
    type: condition
    task:
      id: 4f6b8a30-2a11-4924-8ac8-ce0c3bddcb62
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "14"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: GoogleCloudPubSub.Topics.name
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: f06afeff-84cd-42b4-8e16-07165e1a0744
    type: regular
    task:
      id: f06afeff-84cd-42b4-8e16-07165e1a0744
      version: -1
      name: google-cloud-pubsub-topic-publish-message
      script: '|||google-cloud-pubsub-topic-publish-message'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      attributes: {}
      data:
        simple: 'The time is: ${TimeNow}'
      project_id:
        simple: gcp-integrations
      topic_id:
        simple: dmst-test-topic
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: bea75f13-2bd5-4f73-8dd6-40357ce82062
    type: condition
    task:
      id: bea75f13-2bd5-4f73-8dd6-40357ce82062
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "6"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: GoogleCloudPubSubPublishedMessages.messageId
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: GoogleCloudPubSubPublishedMessages.topic
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: f0a57786-9b8f-44de-8c33-6d312a5f86fc
    type: regular
    task:
      id: f0a57786-9b8f-44de-8c33-6d312a5f86fc
      version: -1
      name: google-cloud-pubsub-topic-subscription-get-by-name
      script: '|||google-cloud-pubsub-topic-subscription-get-by-name'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      project_id:
        simple: gcp-integrations
      subscription_id:
        simple: test_sub_2
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "7":
    id: "7"
    taskid: 96f4c128-c120-4c4d-8c92-850e059d01c6
    type: condition
    task:
      id: 96f4c128-c120-4c4d-8c92-850e059d01c6
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "8"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: GoogleCloudPubSubSubscriptions.ackDeadlineSeconds
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: GoogleCloudPubSubSubscriptions.expirationPolicy.ttl
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: GoogleCloudPubSubSubscriptions.messageRetentionDuration
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: GoogleCloudPubSubSubscriptions.name
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: GoogleCloudPubSubSubscriptions.topic
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "8":
    id: "8"
    taskid: 26424551-d04e-490d-8239-9d44a3db05ea
    type: regular
    task:
      id: 26424551-d04e-490d-8239-9d44a3db05ea
      version: -1
      name: google-cloud-pubsub-topic-subscriptions-list
      script: '|||google-cloud-pubsub-topic-subscriptions-list'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      page_size: {}
      page_token: {}
      project_id:
        simple: gcp-integrations
      topic_id: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1770
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "9":
    id: "9"
    taskid: bc80f66e-9b0a-4ab5-8119-8ad47440baca
    type: condition
    task:
      id: bc80f66e-9b0a-4ab5-8119-8ad47440baca
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "10"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: GoogleCloudPubSubSubscriptions.ackDeadlineSeconds
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: GoogleCloudPubSubSubscriptions.expirationPolicy.ttl
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: GoogleCloudPubSubSubscriptions.messageRetentionDuration
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: GoogleCloudPubSubSubscriptions.name
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: GoogleCloudPubSubSubscriptions.topic
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: GoogleCloudPubSubSubscriptions.pushConfig.pushEndpoint
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1945
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "10":
    id: "10"
    taskid: 3d5e7b51-d89d-4934-871f-78c8e5fe9e17
    type: regular
    task:
      id: 3d5e7b51-d89d-4934-871f-78c8e5fe9e17
      version: -1
      name: google-cloud-pubsub-topic-messages-pull
      script: '|||google-cloud-pubsub-topic-messages-pull'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      ack:
        simple: "true"
      max_messages:
        simple: "1"
      project_id:
        simple: gcp-integrations
      subscription_id:
        simple: test_sub_2
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2120
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "11":
    id: "11"
    taskid: 4167efa7-a161-457e-8fbe-780172f9e231
    type: condition
    task:
      id: 4167efa7-a161-457e-8fbe-780172f9e231
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "12"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: GoogleCloudPubSubPulledMessages.data
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: GoogleCloudPubSubPulledMessages.messageId
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: GoogleCloudPubSubPulledMessages.publishTime
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2295
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "12":
    id: "12"
    taskid: cf0905bc-bc52-4825-8e6b-0bb49ba2a200
    type: regular
    task:
      id: cf0905bc-bc52-4825-8e6b-0bb49ba2a200
      version: -1
      name: google-cloud-pubsub-topic-subscription-create
      script: '|||google-cloud-pubsub-topic-subscription-create'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      ack_deadline_seconds: {}
      expiration_ttl:
        simple: 86400s
      labels: {}
      message_retention_duration: {}
      project_id:
        simple: gcp-integrations
      push_attributes: {}
      push_endpoint: {}
      retain_acked_messages: {}
      subscription_id:
        simple: test_sub_${TimeNowUnix}
      topic_id:
        simple: dmst-test-topic
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2470
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "13":
    id: "13"
    taskid: 86eced98-32f5-4954-85e5-827e5e6044a1
    type: title
    task:
      id: 86eced98-32f5-4954-85e5-827e5e6044a1
      version: -1
      name: Test Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2645
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "14":
    id: "14"
    taskid: 87bf8549-d762-4f9e-870d-b1d303154cfd
    type: regular
    task:
      id: 87bf8549-d762-4f9e-870d-b1d303154cfd
      version: -1
      name: Get Time Now
      description: |
        Retrieves the current date and time.
      scriptName: GetTime
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      contextKey: {}
      date: {}
      dateFormat: {}
      hoursAgo: {}
      minutesAgo: {}
      monthsAgo: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "15":
    id: "15"
    taskid: 8e5e372f-082c-4852-81b8-47441b80c819
    type: regular
    task:
      id: 8e5e372f-082c-4852-81b8-47441b80c819
      version: -1
      name: Clean test_sub_2 Queue
      script: '|||google-cloud-pubsub-topic-messages-pull'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      ack:
        simple: "true"
      max_messages:
        simple: "100"
      project_id:
        simple: gcp-integrations
      subscription_id:
        simple: test_sub_2
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2660,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
