id: 2e000099-7f01-4a14-88a0-062f633ee89f
version: 12
name: Smokescreen IllusionBLACK Default
description: Enriches IllusionBLACK incidents with events related to the incident.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 4d5f9176-0600-47be-8fc4-043532654d78
    type: start
    task:
      id: 4d5f9176-0600-47be-8fc4-043532654d78
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "1":
    id: "1"
    taskid: 52d1089e-d0a9-45e4-8a06-66635ca9144c
    type: regular
    task:
      id: 52d1089e-d0a9-45e4-8a06-66635ca9144c
      version: -1
      name: Get IllusionBLACK events for the incident
      description: 'Fetches IllusionBLACK events from a llist of event IDs. '
      script: Smokescreen_IllusionBLACK|||illusionblack-get-event-by-id
      type: regular
      iscommand: true
      brand: Smokescreen_IllusionBLACK
    scriptarguments:
      id:
        simple: ${inputs.event_ids}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 275,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
inputs:
- key: event_ids
  value:
    simple: ${incident.illusionblackevents}
  required: true
  description: IllusionBLACK event IDs for an incident
outputs: []
