id: QRadarCorrelationLog
version: -1
name: QRadarCorrelationLog
description: This playbook get the correlation logs of multiple QIDs.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: a374610e-f2d9-44e9-8f43-5104340acc90
    type: start
    task:
      id: a374610e-f2d9-44e9-8f43-5104340acc90
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ""
    nexttasks:
      '#none#':
      - "3"
      - "4"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: 030c4d55-47d6-4753-8e43-3518cf8ba512
    type: playbook
    task:
      id: 030c4d55-47d6-4753-8e43-3518cf8ba512
      version: -1
      name: Run Correlation Log Search
      description: This playbook runs a QRadar query and return its results to the
        context.
      playbookName: QRadarFullSearch
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      headers: {}
      interval:
        simple: "1"
      query_expression:
        simple: "\t\tselect qid QID,\n\t\tsourceip as \"SourceIP\",\n\t\tdestinationip
          as \"DestinationIP\",\n\t\teventcount as \"EventCount\",\n\t\tsourceport
          as \"SourcePort\",\n\t\tusername as \"Username\",\n\t\tstarttime as \"StartTime\",\n\t\tdestinationport
          as \"DestinationPort\",\n\t\tmagnitude as \"Magnitude\",\n\t\tidentityip
          as \"IdentityIP\",\n\t\tCATEGORYNAME(category) as \"Category\",\n\t\tPROTOCOLNAME(protocolid)
          as \"ProtocolName\",\n\t\tLOGSOURCENAME(logsourceid)${inputs.additionalQueryFields}\n\t\tfrom
          events where (RULENAME(${inputs.QID}) ILIKE '%') AND \"CRE Name\" IS NULL AND INOFFENSE(${inputs.OffenseID})\nLIMIT ${inputs.MaxLogsCount}\n
          START '${inputs.OffenseStartTime}'"
      range: {}
      timeout:
        simple: "600"
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
      forEach: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: a4bf60f2-3d38-47fb-856d-e3aed2c5d2a5
    type: title
    task:
      id: a4bf60f2-3d38-47fb-856d-e3aed2c5d2a5
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: 444a57ad-0ecb-45f9-8557-0489a7d7b167
    type: condition
    task:
      id: 444a57ad-0ecb-45f9-8557-0489a7d7b167
      version: -1
      name: Is OnlyCRE or ALL
      type: condition
      iscommand: false
      brand: ""
      description: ""
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "1"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: inList
          left:
            value:
              simple: inputs.GetOnlyCREEvents
            iscontext: true
          right:
            value:
              simple: OnlyCRE,All
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: 9fbf87b8-8467-4472-83f3-e3ffaf9f269f
    type: condition
    task:
      id: 9fbf87b8-8467-4472-83f3-e3ffaf9f269f
      version: -1
      name: Is OnlyCRE or ALL
      type: condition
      iscommand: false
      brand: ""
      description: ""
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "5"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: inList
          left:
            value:
              simple: inputs.GetOnlyCREEvents
            iscontext: true
          right:
            value:
              simple: OnlyCRE,All
    view: |-
      {
        "position": {
          "x": 592.5,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: 2b985b68-0ed7-4df5-8e48-6a9639850803
    type: playbook
    task:
      id: 2b985b68-0ed7-4df5-8e48-6a9639850803
      version: -1
      name: Run Correlation Log Search
      description: This playbook runs a QRadar query and return its results to the
        context.
      playbookName: QRadarFullSearch
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      headers: {}
      interval:
        simple: "1"
      query_expression:
        simple: "\t\tselect qid QID,\n\t\tsourceip as \"SourceIP\",\n\t\tdestinationip
          as \"DestinationIP\",\n\t\teventcount as \"EventCount\",\n\t\tsourceport
          as \"SourcePort\",\n\t\tusername as \"Username\",\n\t\tstarttime as \"StartTime\",\n\t\tdestinationport
          as \"DestinationPort\",\n\t\tmagnitude as \"Magnitude\",\n\t\tidentityip
          as \"IdentityIP\",\n\t\tCATEGORYNAME(category) as \"Category\",\n\t\tPROTOCOLNAME(protocolid)
          as \"ProtocolName\",\n\t\tLOGSOURCENAME(logsourceid)${inputs.additionalQueryFields}\n\t\tfrom
          events where (RULENAME(${inputs.QID}) ILIKE '%') AND \"CRE Name\" <> NULL AND INOFFENSE(${inputs.OffenseID})
          \nLIMIT ${inputs.MaxLogsCount}\n
          START '${inputs.OffenseStartTime}'"
      range: {}
      timeout:
        simple: "600"
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
      forEach: true
    view: |-
      {
        "position": {
          "x": 705,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 560,
        "width": 1035,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: QID
  value: {}
  required: true
  description: The correlation QID.
  playbookInputQuery: null
- key: OffenseStartTime
  value: {}
  required: true
  description: The offense start time.
  playbookInputQuery: null
- key: OffenseID
  value: {}
  required: true
  description: The offense ID.
  playbookInputQuery: null
- key: additionalQueryFields
  value: {}
  required: false
  description: "Add more fields for basic query (a list with comma separators)"
  playbookInputQuery: null
- key: GetOnlyCREEvents
  value:
    simple: OnlyCRE
  required: false
  description: |-
    If value "OnlyCRE" get only events made by CRE.
    Values can be "OnlyCRE", "OnlyNotCRE", "All".
  playbookInputQuery: null
- key: MaxLogsCount
  value:
    simple: "20"
  required: false
  description: 'Maximum number of log entires to query from QRadar (default: 20)'
  playbookInputQuery: null
outputs: []
fromversion: 4.5.0
