id: Smokescreen_IllusionBLACK-Test
name: Smokescreen_IllusionBLACK-Test
version: -1
fromversion: 5.0.0
starttaskid: '0'
tasks:
  '0':
    id: '0'
    taskid: '0'
    type: start
    task:
      id: '0'
      version: -1
      name: ''
      iscommand: false
      brand: ''
      description: ''
    nexttasks:
      '#none#':
      - '1'
    separatecontext: false
    view: '{"position": {"x": 50, "y": 50}}'
    note: false
    timertriggers: []
    ignoreworker: false
  '1':
    id: 1
    taskid: '1'
    type: regular
    task:
      id: '1'
      version: -1
      name: DeleteContext
      description: ''
      script: DeleteContext
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '2'
    scriptarguments:
      all:
        simple: yes
    separatecontext: false
    view: '{"position": {"x": 50, "y": 200}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '2':
    id: 2
    taskid: '2'
    type: regular
    task:
      id: '2'
      version: -1
      name: illusionblack-get-ad-decoys
      description: ''
      script: '|||illusionblack-get-ad-decoys'
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '3'
    scriptarguments: {}
    separatecontext: false
    view: '{"position": {"x": 50, "y": 400}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '3':
    id: '3'
    taskid: '3'
    type: condition
    task:
      id: '3'
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      description: ''
      brand: ''
    nexttasks:
      yes:
      - '4'
    separatecontext: false
    conditions:
    - label: yes
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: IllusionBlack.AdDecoy
            iscontext: true
    view: '{"position": {"x": 50, "y": 600}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '4':
    id: 4
    taskid: '4'
    type: regular
    task:
      id: '4'
      version: -1
      name: illusionblack-get-network-decoys
      description: ''
      script: '|||illusionblack-get-network-decoys'
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '5'
    scriptarguments: {}
    separatecontext: false
    view: '{"position": {"x": 50, "y": 800}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '5':
    id: '5'
    taskid: '5'
    type: condition
    task:
      id: '5'
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      description: ''
      brand: ''
    nexttasks:
      yes:
      - '6'
    separatecontext: false
    conditions:
    - label: yes
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: IllusionBlack.NetworkDecoy
            iscontext: true
    view: '{"position": {"x": 50, "y": 1000}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '6':
    id: 6
    taskid: '6'
    type: regular
    task:
      id: '6'
      version: -1
      name: illusionblack-get-ti-decoys
      description: ''
      script: '|||illusionblack-get-ti-decoys'
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '7'
    scriptarguments: {}
    separatecontext: false
    view: '{"position": {"x": 50, "y": 1200}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '7':
    id: '7'
    taskid: '7'
    type: condition
    task:
      id: '7'
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      description: ''
      brand: ''
    nexttasks:
      yes:
      - '8'
    separatecontext: false
    conditions:
    - label: yes
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: IllusionBlack.TIDecoy
            iscontext: true
    view: '{"position": {"x": 50, "y": 1400}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '8':
    id: 8
    taskid: '8'
    type: regular
    task:
      id: '8'
      version: -1
      name: illusionblack-is-host-decoy
      description: ''
      script: '|||illusionblack-is-host-decoy'
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '9'
    scriptarguments: {}
    separatecontext: false
    view: '{"position": {"x": 50, "y": 1600}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '9':
    id: 9
    taskid: '9'
    type: regular
    task:
      id: '9'
      version: -1
      name: illusionblack-is-user-decoy
      description: ''
      script: '|||illusionblack-is-user-decoy'
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '10'
    scriptarguments: {}
    separatecontext: false
    view: '{"position": {"x": 50, "y": 1800}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '10':
    id: 10
    taskid: '10'
    type: regular
    task:
      id: '10'
      version: -1
      name: illusionblack-is-subdomain-decoy
      description: ''
      script: '|||illusionblack-is-subdomain-decoy'
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '11'
    scriptarguments: {}
    separatecontext: false
    view: '{"position": {"x": 50, "y": 2000}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '11':
    id: 11
    taskid: '11'
    type: regular
    task:
      id: '11'
      version: -1
      name: illusionblack-get-events
      description: ''
      script: '|||illusionblack-get-events'
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '12'
    scriptarguments: {}
    separatecontext: false
    view: '{"position": {"x": 50, "y": 2200}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '12':
    id: '12'
    taskid: '12'
    type: condition
    task:
      id: '12'
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      description: ''
      brand: ''
    nexttasks:
      yes:
      - '13'
    separatecontext: false
    conditions:
    - label: yes
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: IllusionBlack.Events
            iscontext: true
    view: '{"position": {"x": 50, "y": 2400}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '13':
    id: '13'
    taskid: '13'
    type: title
    task:
      id: '13'
      version: -1
      name: Test Done
      type: title
      iscommand: false
      brand: ''
      description: ''
    separatecontext: false
    view: '{"position": {"x": 50, "y": 2600}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
view: '{"linkLabelsPosition": {}, "paper": {"dimensions": {"height": 200, "width":
  380, "x": 50, "y": 50}}}'
inputs: []
outputs: []
